### ISSUE TITLE
如何部署到vercel

### ISSUE THREAD

**Issue by Cara-Hall** [Qikaile/markdown-online-editor#1]
看到项目提供的demo是vercel的，尝试使用默认参数部署到vercel失败了。

希望能有个简明的部署教程，十分感谢！

**Comment by Qikaile** [comment]
> 看到项目提供的demo是vercel的，尝试使用默认参数部署到vercel失败了。
> 
> 希望能有个简明的部署教程，十分感谢！

- 大概率是Node版本的问题吧！你修改这个再重新部署看看，没看见截图不太清楚
![Snipaste_2023-03-28_20-04-40](https://user-images.githubusercontent.com/51025570/228231717-a4987f1b-cb3a-4d08-9523-ee3c682cb6e9.jpg)

**Comment by Cara-Hall** [comment]
@Qikaile 将Node版本改成14.x部署成功。

不过log里报了以下错误，虽然对部署没影响，还是想请教下如何解决。
```
[21:57:40.996] Module Warning (from ./node_modules/eslint-loader/index.js):
[21:57:40.996] error: Insert `<!--·@format·-->⏎⏎` (prettier/prettier) at src/components/PreviewVditor.vue:1:1:
[21:57:40.996] > 1 | <template>
[21:57:40.996]     | ^
[21:57:40.996]   2 |   <div class="preview-vditor" v-loading="isLoading" element-loading-text="正在努力，请稍候...">
[21:57:40.996]   3 |     <div id="khaleesi" class="vditor-preview" />
[21:57:40.996]   4 |   </div>
[21:57:40.996] 
[21:57:40.996] 
[21:57:40.996] 1 error found.
[21:57:40.996] 1 error potentially fixable with the `--fix` option.
[21:57:40.996] 
[21:57:40.996] Module Warning (from ./node_modules/eslint-loader/index.js):
[21:57:40.996] error: Replace `⏎········href="/"⏎········class="header-link"⏎······` with `·href="/"·class="header-link"` (prettier/prettier) at src/pages/partials/HeaderNav.vue:6:9:
[21:57:40.997]   4 |   <section class="header-wrapper">
[21:57:40.997]   5 |     <h1 class="header-area">
[21:57:40.998] > 6 |       <a
[21:57:40.998]     |         ^
[21:57:40.998]   7 |         href="/"
[21:57:40.998]   8 |         class="header-link"
[21:57:40.998]   9 |       >
[21:57:40.998] 
[21:57:40.998] 
[21:57:40.998] error: Replace `⏎··········href="https://www.qikaile.tk/about"⏎··········class="header-link"⏎········` with `·href="https://www.qikaile.tk/about"·class="header-link"` (prettier/prettier) at src/pages/partials/HeaderNav.vue:14:11:
[21:57:40.999]   13 |       <div class="button-group">
[21:57:40.999] > 14 |         <a
[21:57:40.999]      |           ^
[21:57:40.999]   15 |           href="https://www.qikaile.tk/about"
[21:57:40.999]   16 |           class="header-link"
[21:57:40.999]   17 |         >
[21:57:40.999] 
[21:57:40.999] 
[21:57:40.999] error: Replace `⏎··········href="https://box.tjys.ml"⏎··········class="header-link"⏎··········target="_blank"⏎··········rel="noopener"⏎········` with `·href="https://box.tjys.ml"·class="header-link"·target="_blank"·rel="noopener"` (prettier/prettier) at src/pages/partials/HeaderNav.vue:27:11:
[21:57:40.999]   25 |           </span>
[21:57:40.999]   26 |         </router-link>
[21:57:40.999] > 27 |         <a
[21:57:40.999]      |           ^
[21:57:40.999]   28 |           href="https://box.tjys.ml"
[21:57:41.000]   29 |           class="header-link"
[21:57:41.000]   30 |           target="_blank"
[21:57:41.000] 
[21:57:41.000] 
[21:57:41.000] error: Replace `⏎··········href="https://github.com/Qikaile/markdown-online-editor"⏎··········class="header-link"⏎········` with `·href="https://github.com/Qikaile/markdown-online-editor"·class="header-link"` (prettier/prettier) at src/pages/partials/HeaderNav.vue:37:11:
[21:57:41.000]   35 |           </span>
[21:57:41.000]   36 |         </a>
[21:57:41.000] > 37 |         <a
[21:57:41.000]      |           ^
[21:57:41.000]   38 |           href="https://github.com/Qikaile/markdown-online-editor"
[21:57:41.000]   39 |           class="header-link"
[21:57:41.000]   40 |         >
[21:57:41.000] 
[21:57:41.000] 
[21:57:41.000] 4 errors found.
[21:57:41.001] 4 errors potentially fixable with the `--fix` option.
```
